---
- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
- name: Mask Firewalld
  systemd:
    name: firewalld
    masked: yes
- name : Install epel
  yum: name=epel-release
- name: Install net-tools
  yum:
    state: present
    name: net-tools
- name: Install  packages
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages_to_install }}"
- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"