---
- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
- name: Mask Firewalld
  systemd:
    name: firewalld
    masked: yes
- name : Install epel
  yum: name=epel-release
- name: Install net-tools
  yum:
    state: present
    name: net-tools
- name: Install  packages
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages_to_install }}"
- name: add hostname to /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]0[.]1.*"
    line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} {{ comment }}"
    state: present
    backup: yes
- name: add IP address of all hosts to /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: ".* {{ item }} {{ comment }}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }} {{ item }} {{ comment }}"
    state: present
    backup: yes
  when: ansible_hostname != item
  loop: "{{ query('inventory_hostnames', 'all') }}"