---
- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
- name: Mask Firewalld
  systemd:
    name: firewalld
    masked: yes
- name : Install epel
  yum: name=epel-release
- name: Install net-tools
  yum:
    state: present
    name: net-tools
- name: Install  packages
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages_to_install }}"
- name: add hostname to /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]0[.]1.*"
    line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} {{ comment }}"
    state: present
    backup: yes
- name: Generate /etc/hosts for all hosts
  lineinfile: 
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  with_items: "{{ groups.all }}"